# Generated by Django 4.2.4 on 2023-08-11 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_options_alter_priority_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priority',
            name='name',
            field=models.CharField(choices=[(3, 'High'), (2, 'Medium'), (1, 'Low')], max_length=50),
        ),
    ]
