# Generated by Django 4.2.4 on 2023-08-11 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_remove_priority_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[(3, 'High'), (2, 'Medium'), (1, 'Low')], max_length=50),
        ),
        migrations.DeleteModel(
            name='Priority',
        ),
    ]
