# Generated by Django 4.2.4 on 2023-08-11 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_task_options_priority_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priority',
            name='level',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='priority',
            name='name',
            field=models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=50),
        ),
    ]
