# Generated by Django 4.2.4 on 2023-08-11 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_alter_task_options_remove_task_priority_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': [models.Case(models.When(completed=False, then=models.Value(1)), default=models.Value(0), output_field=models.BooleanField()), 'due_date']},
        ),
    ]
